backend:
  name: github
  repo: cleveland4solidarity/cleveland4solidarity.github.io
  branch: master
  site_domain: steward-bar-82035.netlify.com
media_folder: "src/assets/img/uploads"
collections:
  - name: "updates" # Used in routes, e.g. /admin/collections/blog
    label: "Updates" # Used in the UI
    folder: "src/_updates" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "update"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "people" # Used in routes, e.g. /admin/collections/blog
    label: "People" # Used in the UI
    folder: "src/_people" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "person"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Birthdate", name: "birthdate", widget: "date", default: "1992-09-10", format: "YYYY-MM-DD"}
      - {label: "Bio", name: "body", widget: "markdown"}
      - {label: "Writing Address", name: "writing-address", widget: "markdown"}
      - {label: "Writing Instructions", name: "writing-instructions", widget: "markdown"}
      - {label: "Link to Booklist", name: "booklist-url", widget: "string"}
      - name: "photos"
        label: "Photos"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Photo", name: "photo", widget: "image"}
  - name: "pages" # Used in routes, e.g. /admin/collections/blog
    label: "Pages" # Used in the UIx
    folder: "src/_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "pages"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "settings" # Used in routes, e.g. /admin/collections/blog
    label: "Settings" # Used in the UI
    folder: "src/_settings" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "settings" # Filename template i.e. YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {name: "title", widget: "hidden", default: "Settings"}
      - {name: "layout", widget: "hidden", default: "settings"}
      - name: "site"
        widget: "object"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
      - name: "social"
        widget: "object"
        fields:
          - {label: "Facebook Link", name: "facebook", widget: "string"}
          - {label: "Twitter Link", name: "twitter", widget: "string"}
          - {label: "Fundraising Link", name: "fund", widget: "string"}
